### ISSUE TITLE
Problems with reloading in development

### ISSUE THREAD

**Issue by thomasklemm** [glennreyes/graphpack#38]
Thanks for this amazing project, @glennreyes!

Reloading doesn't seem to happen properly on my machine. Compilation seems to happen correctly, but the old server code continues to run.

Setup:
- Followed the first steps of the Readme until running a development server. 
- [yarn.lock](https://gist.github.com/thomasklemm/97e871371bdaefa646cb3bec6bd5737c) for package versions

Output in the terminal:
```
 DONE  Compiled successfully in 160ms                                                                                                                                        22:33:26

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at resolve (/Users/thomasklemm/Code/experiments/testing-graphpack/node_modules/apollo-server/dist/index.js:74:28)
    at new Promise (<anonymous>)
    at ApolloServer.<anonymous> (/Users/thomasklemm/Code/experiments/testing-graphpack/node_modules/apollo-server/dist/index.js:72:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/thomasklemm/Code/experiments/testing-graphpack/node_modules/apollo-server/dist/index.js:4:58)
Emitted 'error' event at:
    at Server.emit (events.js:182:13)
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by thomasklemm** [comment]
I've verified that no other process is running on port 4000, so I guess it must be the running instance blocking the reloading.

**Comment by glennreyes** [comment]
Could you please put a minimal reproducible example to codesandbox? Happy to help, thanks!

**Comment by thomasklemm** [comment]
Couldn't get an example breaking on codesandbox, so I guess this must be related to my local setup somehow. Thus closing the issue. Thanks for your work on graphpack again, @glennreyes, and the quick reply!
