### ISSUE TITLE
cosmiconfig(...).search() is not a function

### ISSUE THREAD

**Issue by glenndevenish** [glennreyes/graphpack#39]
I've run into an error, but I'm not sure what has triggered it. Here is the error message:

```
 DONE  Compiled successfully in 1121ms                                                        
...\build\index.js:103
const explorer = cosmiconfig('graphpack').search();
                                          ^

TypeError: cosmiconfig(...).search is not a function
    at Object../node_modules/graphpack/config/index.js (...\build\index.js:103:43)
    at __webpack_require__ (...\build\index.js:21:30)
    at Module../node_modules/graphpack/lib/server.js (...\build\index.js:240:65)
    at __webpack_require__ (...\build\index.js:21:30)
    at Object.0 (...\build\index.js:700:18)
    at __webpack_require__ (...\build\index.js:21:30)
    at ...\build\index.js:85:18
    at Object.<anonymous> (...\build\index.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

I've tried running `graphpack` and `graphpack build` then `node ./build/index.js`, but both methods throw this error.

**Comment by glenndevenish** [comment]
I've just sent you an invite to a mvp repo...

Thanks

**Comment by glennreyes** [comment]
Hi @glenndevenish!
Unfortunately I only have limited time and can't look into private codebases atm. If you're still seeing the error please create an example with CodeSandbox so that also other people who are watching this issue could potentially find the problem.

Thank you!
