### ISSUE TITLE
Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'

### ISSUE THREAD

**Issue by DarkSuniuM** [glennreyes/graphpack#40]
Hey
I just started to learn about `GraphQL`
Using `graphpack` was suggested by a guide on dev.to blog

I initialized a new project using `yarn`
Installed `graphpack` as suggested using `yarn add -D graphpack`
Created `src` dir, created `index.js`, `resolvers.js` and `schema.graphql` inside `src` just like the demo on CodeSandBox,
I added `start` to `scripts` in `package.json`
Tried to run it using `yarn start`/`yarn run start`

```
 DONE  Compiled successfully in 182ms                                 2:54:48 AM

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/alireza/Desktop/Tutorials/GraphQL/test/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

I search alot in google, they were suggesting to install `core-js` global, even did that but didn't fix my problem

At last I took a look at your Demo, in `package.json` it was `graphpack 1.0.2`, So I tried the same stuff, but instead of `yarn add -D graphpack` I used `yarn add -D graphack@1.0.2` and the problem got fixed.

OS: `Archlinux`
Node Version: `10.15.1`
Yarn Version: `1.13.0`
NPM Version: `6.8.0`

What can cause the problem with graphpack 1.0.6!?

**Comment by glennreyes** [comment]
Hi, thank you for filing this!

It's related to https://github.com/apollographql/apollo-tooling/issues/962 and added the fix with https://github.com/glennreyes/graphpack/commit/aa9db673850b38ff7b1925f64e4103bce9c7f022.

Please upgrade to the latest version with `yarn add --dev graphpack`.
